eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8773
spring:
  application:
    name: service-zuul
zuul:
  routes:

    api-f:
      path: /api-f/**
      serviceId: service-feign
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon